hide_download: true
hide_download_original: null
leftnav:
- identifier: ea9623ad-61a1-5125-cef5-dd28e977562a
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: a98dadc0-08ca-d396-cba0-0ec45bfdd378
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 4eb7457e-6481-c28d-324c-a08407ab111f
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 2f06eac9-28af-4e7b-6f78-8c142d9f8b16
  name: Recitations
  pageRef: /pages/recitations
  weight: 40
- identifier: f4965611-3d3a-fc2b-2a0c-969ecad00d3e
  name: Labs
  pageRef: /pages/labs
  weight: 50
- identifier: e768ed94-4857-57f1-dfe8-1444f83fae39
  name: Assignments
  pageRef: /pages/assignments
  weight: 60
- identifier: 5e806096-43af-a7ce-d3bd-b9e63faabc78
  name: Exams
  pageRef: /pages/exams
  weight: 70
